package de.rafmon.aoc.twentythree.one;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class Trebuchet {

	public static final String INPUT = "fivepqxlpninevh2xxsnsgg63pbvdnqptmg\r\n"
			+ "eight8zlctbmsixhrvbpjb84nnmlcqkzrsix\r\n" + "hkxqfrqmsixfplbkpkdfzzszjxmdjtdkjlprrvr3gghlrqckqtbng\r\n"
			+ "zkjkctxvssix1dqb22five\r\n" + "4dtlmkfnm\r\n" + "four539tkqrc\r\n"
			+ "blxqb7onetvmfjlvglrnbtdonegfourfour\r\n" + "lqzrclnlzrvdstgtoneseven1xrvdchn29\r\n"
			+ "tczmtfkqhthreetwo7five\r\n" + "kncvqpzdtfs7\r\n" + "6seveneighttwonine2\r\n"
			+ "sixbfgxndseven9nvzr6ftsqb1\r\n" + "ddgjgcrssevensix37twooneightgt\r\n"
			+ "zclvhfz91zbdkrreightbzqttdxrone\r\n" + "five18twofiveclqqsrsfdbrt\r\n" + "ninedflcfblvjhr3\r\n"
			+ "32eightnmlv5lgbckz\r\n" + "nine7xqz81dtpld\r\n" + "2tmbddjl9cgcrvnrpgl\r\n" + "5twofivedlk1pfjjmctjh\r\n"
			+ "nvcchgjnine9sixtwompfrp\r\n" + "685\r\n" + "54two7twobsfpkxjninefoureight\r\n"
			+ "fgsvpxcx4zzxfqdkssixgbssrqmnpz9threethreefour\r\n" + "three3sixnine38bprqqkpdr6seven\r\n"
			+ "xgmc3sixthree1\r\n" + "3eight2twojqsvbtftp\r\n" + "six7sixtwos1mhzfpzmhfcslrmfive\r\n"
			+ "bmxmxzldtngrgbt538jzqvjlrrc4\r\n" + "sevenxqzcrgzvfiveggxlxf4fiveppvrxjkdk9\r\n" + "one8six\r\n"
			+ "fourdlhgvx1onesix\r\n" + "onelpbxfnjm28gjjs5\r\n" + "pdb69six6cdxmxxbfour5five\r\n"
			+ "eightjndqhjzv43five631\r\n" + "9fourldr92eight\r\n" + "three1sevensrxzlnxrnine7four\r\n"
			+ "eightfive4bldzgtpvslgkrmlmkftpone\r\n" + "22357fourone6\r\n"
			+ "sixrzhgvzsjsix9dbldsevenfivedtnbkjjxfc\r\n" + "mcgfpfh1three\r\n" + "ninetwo1\r\n"
			+ "sqgtvmcvbfsslsdnine19three1two\r\n" + "f5nine7six\r\n" + "1sbggj\r\n" + "5eight56342h\r\n"
			+ "3onezdfsvngvjg4fqeight\r\n" + "sixncfrkbqthreeqsbpvspjt4\r\n" + "fjseventwo4k\r\n" + "five8five\r\n"
			+ "4oneone14\r\n" + "prpnzmnsjsfivetdrqpt54\r\n" + "2threefour2fourrkkndqzq\r\n"
			+ "lreightfourfour12sfjkjmbntkgfjv\r\n" + "sixfour93\r\n" + "eightfivetwo1one\r\n"
			+ "three5eightjk5twothreeseven\r\n" + "tz62twofivetclnxfp8dhsxzgpxhsfhx\r\n" + "fivefivecrjhmbrk6three\r\n"
			+ "58fiveseven3five\r\n" + "nine4six6hqmqqqbktkfvmb\r\n" + "7five8k\r\n" + "5kbfjmqppvrbjdkc\r\n"
			+ "hkpchj2gknjhvc\r\n" + "7twosix\r\n" + "2kltwo\r\n" + "six6vlmhdmvtdsix\r\n" + "xqtpnglkktvpktfive1\r\n"
			+ "9one91\r\n" + "vbrcfmjeight4qmtzmpqhsninejdmvzpdtpq2\r\n" + "3eightzdcrvqeightl7nsbpdrczdrnine\r\n"
			+ "nine6hkfeight9\r\n" + "73pqqqsixone7bvl\r\n" + "1threeeight9six\r\n" + "46one9smxbqzrppr56six\r\n"
			+ "njoneight27fourthreevtxf51\r\n" + "fivekbdfkfjk2\r\n" + "two1lxdpqtq2xhffmbcbll1\r\n"
			+ "tlngnjqlkmcx44mnhpbg9threepngzm2\r\n" + "nine4qgccpx1nine\r\n" + "four8515svqscfsds\r\n"
			+ "5fllxvlhqcp618four6kkone\r\n" + "nsxbrczm566cldngf4qncqmcvvrgztxrr\r\n"
			+ "1seveneighttbrlnfbdkzkppnineqppcdvnpthree\r\n" + "fiveninesevenfbsz1crjpbncrh\r\n" + "12jsdmvonesth\r\n"
			+ "4ngrc5\r\n" + "ffpknzsjcgrdxfxjrneights3five\r\n" + "66nfcsztrtmdf\r\n" + "5three5twojmsxvpczpd5\r\n"
			+ "pb1fournjgkfcbn2shzgpnfx\r\n" + "rzphlccmdseven7fxfiveone\r\n" + "2foureight25\r\n"
			+ "n4jdlrjkfppfive4phvcfnineeight\r\n" + "fivedfplsxxmjsmsrxbrbv3sixsix\r\n"
			+ "pnbpqfxsdhlkklmk4seventhree2\r\n" + "8seven7sixgplpldf9\r\n" + "zx13cxmckxfbmsxlssrttwo\r\n"
			+ "15sfs\r\n" + "hktnxtwothree3pqzzkfdrhjmhmk6onexnhnvhx\r\n" + "13vz1bgbbgcljq8d\r\n" + "hrtfeight822\r\n"
			+ "5threefourjdmrnhrvmkfiveeight9seven4\r\n" + "six13zxtcms\r\n" + "6966\r\n"
			+ "xcslbzkmv3pmlrnnn471nine\r\n" + "nzmslhzlh5zdnfone39cp2\r\n" + "9sixfourtwothreefivehnxtgnxxbpdmxx\r\n"
			+ "twoqc4lrpgtwo\r\n" + "seven2threeeightwomg\r\n" + "nzsdjhseven97two93xmprjfkrbnbdpvl\r\n"
			+ "pgdszjfive6\r\n" + "sevenhpbnxxntt25fzfrpbndnkmftsbhpjntdxpvcg\r\n"
			+ "nnxktphmqqhxnmfrgqnqqgqtfqqvphn36sixsppns\r\n" + "fourxcp2six9\r\n" + "bz5five2onejttjqmhml7\r\n"
			+ "lrg2ksxhvrfive1twosevenseven5\r\n" + "1jkrllhnmqgvnbvseven\r\n" + "kczvjfzrqh68sevenonethree\r\n"
			+ "onehqvp3\r\n" + "ninecczpd7\r\n" + "fourvlmmhlfrvf4onekpbs\r\n" + "fivezqkcctwoplmrkksfone93three\r\n"
			+ "fhvhfq1tvvt3ckfgtwofour\r\n" + "649twomktwonebx\r\n" + "5fiverbscnmbnnsixfnnlnqq3\r\n" + "3tsjfive\r\n"
			+ "7eight4zsxjftmlbjfourqsgbzdtxfgxbn\r\n" + "mbklhngfthree5\r\n" + "94qqrpvd6\r\n" + "gvkrsxs3\r\n"
			+ "two5c6\r\n" + "51eight5xkgpsxxz\r\n" + "5fjvr\r\n" + "fiveonenine38\r\n" + "one68\r\n"
			+ "7two15cbxmssb25qtcpcjtwonef\r\n" + "two368vtxkdg7\r\n" + "fiveqrjneight1fourfour\r\n"
			+ "six4one9twonetm\r\n" + "msjptzgvbmseven8\r\n" + "4xrklnqqf2sxxt\r\n" + "hsmzcbcgcfivenines88fkf5\r\n"
			+ "1sixeight6onexsdh28\r\n" + "8sevenc267\r\n" + "svlmp99jvbrzh\r\n" + "qvnpsfvvfiveeightpmdpv4\r\n"
			+ "seven6twothreethree\r\n" + "2rgd2\r\n" + "3dsrcdkzndthreexfsldcthreetwo\r\n"
			+ "sixn575pzpmmlxvr41five\r\n" + "qmchsxd6qcmmcjh9q\r\n" + "dqvjfourmqp1six\r\n"
			+ "sbglrkhrhrfldkftzfknblj1twonemm\r\n" + "ninehsgdt38onedhbjzs\r\n" + "5rm\r\n" + "five2mphbljl\r\n"
			+ "kmgmnfddnine1one3three3\r\n" + "ninefour97\r\n" + "7twogmhdmnxfrgnsnxr5fourlone\r\n"
			+ "xnqcdjdsixone463\r\n" + "49xdzq\r\n" + "8qrjgtwo5seventwo2vdz\r\n" + "1xxjvqtrfnfive3\r\n"
			+ "threebfmprszf5dbnmmlggthreepkf797\r\n" + "eightnine645two1fivetknzvmffs\r\n"
			+ "tbjgzkqrzgqseven5nfvqpcqmgsbjfive\r\n" + "1beight5zdvjpcnzxsmseven\r\n" + "7rvmfbjs9krfkhthnkkv\r\n"
			+ "eighttgl21\r\n" + "63onesjfpjgnrg42lbcnccqfvssix\r\n" + "cqxsrzcnine7jgsdssixkmtfljnpstwo3\r\n"
			+ "43qzzklffxl23\r\n" + "1sixsjxmnqfourmbghd\r\n" + "p8njsdrmtzlsixsix7kpbkfq5\r\n"
			+ "sevensixvvqcqrcsix7jtwo\r\n" + "vbgtmkdmjdjlcnine41twotwoksrtkone\r\n" + "fourcnstnbgfive7twof76\r\n"
			+ "ninesixtqsmcrseven28nblqqnjgx\r\n" + "8threeeightcrqm5\r\n" + "xrzgqksx5lbfjmhbnsg3fx8\r\n"
			+ "sevenpnng2xcktsvccpc81eight\r\n" + "673\r\n" + "twofivehqsmrcbt1\r\n"
			+ "6gjmlspgfsmfdvnlpktxpfkprjxxzseven\r\n" + "ninettdbgqznninenine22mmjlstcjbbzone\r\n"
			+ "fourfvdmvsvtwo43vhpmfcqrpfxznkhr\r\n" + "4two96fournineqxckmkseven\r\n" + "lteightwo4\r\n"
			+ "38fivenine678\r\n" + "5nqkfm\r\n" + "cptwone3zlggrkrfkgtwonine4rcpeightfourhxdvtmvqz\r\n"
			+ "ninetwofivefivetwosix29six\r\n" + "one86\r\n" + "6xjxzjdskksix2one\r\n"
			+ "vjssjmqlkzzqfzht5one5leight1four\r\n" + "75sevenfour5\r\n" + "sixthree4eight\r\n"
			+ "sixsixfourspxsvpckcrfr8oneptbdvsfh\r\n" + "54qkgpzqhdr8fqvhj3xpmf65\r\n"
			+ "nqoneight5eight3lcxftzxdqdhftlvkpbgpnine\r\n" + "9dkzvd6\r\n" + "4jhnvmr43one9eight\r\n" + "8bmgfnx\r\n"
			+ "fivesix9xxzjrdkzhb\r\n" + "92h\r\n" + "vlcthreeninetmpbj47vr\r\n" + "grmkzfive6fourdk64\r\n"
			+ "one4six\r\n" + "three3dldnpsctjcbcxrs\r\n" + "5eightsevenjtwonem\r\n"
			+ "fourthreeonelncnqlhvms4eight\r\n" + "8one8six1\r\n" + "7ninegmzsninethree89nq\r\n"
			+ "ninelcsgone11seventhreedzxnpzbnine\r\n" + "4rtnltdfour55kfzl\r\n" + "lnine1threefplpkbjmseven\r\n"
			+ "onetmztjjrksix5fgvxrdfnrcfbfour\r\n" + "ninevtvrrqtrbpxrbqqfsrzglqbdftmz6\r\n" + "kldqgeight9mvfrdl\r\n"
			+ "onejcndvflhfz939519\r\n" + "6btbfdsgzrrzthreexdsix\r\n" + "pdrzkpcbz8four4two\r\n" + "4fglf7rssfive\r\n"
			+ "fiveeight8nhfkeightsix\r\n" + "599\r\n" + "threethreelhb8\r\n" + "sixn7nineonetwottp\r\n"
			+ "one2zqtmbzdqbcdone\r\n" + "8hfleighteightczrsix5three\r\n" + "eight2nineone\r\n"
			+ "2onekkshvstpsix5gddngmcgjr\r\n" + "pnjhrqp212pn3\r\n" + "mpq8fiveseven91clpcshhvrh3\r\n"
			+ "lnkvnnnfddzhfzfpb4htclkp2three5hl\r\n" + "jlmqgdbq7seveneightzc132\r\n" + "19lnfourdrfhsfgqjc\r\n"
			+ "rrcsxzmkt4fivesixseven2fivetwo\r\n" + "8cvfnbtq7\r\n" + "pdrqpsnzbjllknstfgkc88\r\n"
			+ "hpchslzcjskmqfsszrphthrdsgveight2sevensix\r\n" + "fiveninescglgcnxthreeseven6nine\r\n" + "4sixqzvzq\r\n"
			+ "55six5fourfour\r\n" + "xfd1gmpqrjrdeightxfdtldhtgcgj\r\n" + "lchsxqtgdeighttztntqm4\r\n"
			+ "qhgmtjq95ninetwo8seven\r\n" + "8oneeight6eightsix3\r\n" + "7threenine4onedhnthree\r\n"
			+ "8mgkjzvlghf3eightonehhxxn1\r\n" + "eighttwo73threetwodx8\r\n" + "2167\r\n" + "eight7eightcx\r\n"
			+ "fxmntxxltwoninesix8five5\r\n" + "9nmmseven4seven9\r\n" + "ninesgt2dcssdprbstgrrgfmtwofive\r\n"
			+ "6vtg\r\n" + "fourpnmkckmdx45qztcgbbqdqrnine\r\n" + "cbztwosixsjlzjdgrppmk34four2\r\n"
			+ "llhtrzgqxc47five1eight\r\n" + "bhdf315nineoneightzlp\r\n" + "nktvxnllj15six4ninevnffgfq\r\n"
			+ "8fivethreeone794onetwo\r\n" + "gf3bknqbtn1fivexgppseven\r\n" + "16qlgrrjthreegps9\r\n" + "two6three\r\n"
			+ "four7rxsxnvstg9eightthreenine\r\n" + "onethreevgrhtnpdlvnjklqjqj1\r\n" + "3kldmncbzthreesevennine\r\n"
			+ "nine59fnbbnxqcfoursevenfdvmbrs\r\n" + "62sixone3\r\n" + "9four6gdxhzone87eightwohl\r\n"
			+ "4oneskqzhmlz\r\n" + "ptbcbnftfive213\r\n" + "7five2one3four5eight\r\n"
			+ "sevenklqmfhxcqfivellfnlhlkrscxphheightkhpkpqzcl5two\r\n" + "eightbtdvpxphm6ksixsixpjqhsfbmnz\r\n"
			+ "6xgvztvssevenseven\r\n" + "8jjkxdgxtpzvkdzeight\r\n" + "hflhcmjjkmqn6six\r\n" + "six979three\r\n"
			+ "32nine9\r\n" + "nine5pdxt893\r\n" + "oneljbrsdvvg99\r\n" + "foureight3gcxvxxndbonejtqrm\r\n"
			+ "sixtwofive5nfmg76qnlbjtwo\r\n" + "21sixeightfive31ngxzh2\r\n"
			+ "eight7five2lnchgdpqfourdksfhdzmsscnhxksmhbrlgjjsq\r\n" + "cxreightwonine37dpdkngxhhzvxpxqvfqcxj75\r\n"
			+ "xjqcv8zcsqhvzxb\r\n" + "threexgfbjkbdgbpsdg7three7tnqkcjzrh6\r\n"
			+ "3sixtwohtpdjkdthreeninexvgnmgqsdcrplp\r\n" + "44twosevenninembfblv5\r\n" + "mmsm5hh\r\n"
			+ "seventwosix5nmsllddone97\r\n" + "gxhbsf4xp6\r\n" + "foureightonenine769four\r\n" + "9tmfnfxlgt\r\n"
			+ "three4oneonenine7tmg\r\n" + "psp3two\r\n" + "rfrvvqdrpj3fourxktlcp\r\n" + "tnzrzsvrcqffdfxr2four\r\n"
			+ "fourtwosixrnnxsr72\r\n" + "1onetwo2\r\n" + "spdshcnsjkpptl4cpsttwo6\r\n"
			+ "zgjeightwo5five9eightoneeighthzrqzfkrjqlblf\r\n" + "3sevenchkkxnine7\r\n" + "qrxg2one24brccpgxrn\r\n"
			+ "7qgxglktwo\r\n" + "bmnzkzlrfm683fsdfour\r\n" + "8one7qgfmrn\r\n"
			+ "qfxnlfk19ninemjxqzlrbvseventjpgzlfiverpgnv\r\n" + "dxzkndhfeightdhrmbkbzlseventdltstlbmsix4dddgcsk\r\n"
			+ "kmhqhhfpg789ljqzxshtwogm11\r\n" + "569\r\n" + "5tvcpfx\r\n" + "nine6chgjjs5zjxqdninexbdcmccmfive\r\n"
			+ "qzbnineeightfxvxqst6fivexfj4\r\n" + "five14tqxlnsdlbt77\r\n" + "three4grd\r\n" + "1przpcksjqseven7\r\n"
			+ "sevenninefivetgvc7\r\n" + "sixdgfmthsevenspcflmg9four\r\n" + "nineseventwo6eightqjbvbxonefiveone\r\n"
			+ "twothree8hgbzhnsevenfg3\r\n" + "sjlmzxktthreefivexndbnpmvnine4\r\n" + "eightnine3three\r\n"
			+ "mpnfxcv4nineldxdffggqtscvdzq\r\n" + "8dfkvcm\r\n" + "tbvx42l\r\n" + "7one8cjncqdgpsqkhntmr69\r\n"
			+ "sevennknhdmvbcpfbzzs719fivebfhgqrjxfc\r\n" + "1four7threexmpnmcldkktlf\r\n" + "dsbfq3fiverc5one\r\n"
			+ "8jghvmlbmqxdsl3seven8nine9\r\n" + "nineseven2gdzscktwo\r\n" + "seventwostzmlfive49twopgklvfgpkl2\r\n"
			+ "739jrlmqqkkmgghzone8seven\r\n" + "twovzfour9frdgmsftd9\r\n"
			+ "zqoneightonetwomfbbbfpqkmphbonegsdjnzrf8jkkmxvcqt\r\n" + "16four8fjtbhjl3\r\n"
			+ "1nine6hjfcvdxq5dzvjcsevenkbhtgpjclhfive\r\n" + "4onevtxcttthreeeightdmlzhxqbfive\r\n" + "szznone1\r\n"
			+ "6onex2nnb2threeeightwojgf\r\n" + "nine2549\r\n" + "teightwo927jxzjtncnqthree6\r\n" + "dd9\r\n"
			+ "hzqkthree9\r\n" + "jfskpztthree4bxprksix\r\n" + "mjntwonefxmrxnlkeighttwoninerdlnsqcb29\r\n"
			+ "rsgzxtfnineeightsix5\r\n" + "threesdxqq4\r\n" + "472vgjxtknnbmfthree\r\n" + "kxdfive8vxbtkhz6\r\n"
			+ "xltrjrpqqpjvtmfive4\r\n" + "1twofour5954nine7\r\n" + "lppnine3jrfbhcshfvgvhhfkjnpqv\r\n"
			+ "cm74seveneightthreesevenseven\r\n" + "tqszx4eightqhxglflf9tvlpfdconeightq\r\n"
			+ "hmzeightwotwo1775dssdqkxnfbcqrhfqfqfrrgone\r\n" + "ninem734snpvccgqq\r\n"
			+ "onesixdvlvkzqkseven8eightjlr8four\r\n" + "fh785kddmjsdpns\r\n" + "sixptfdbssix2fivenineddxlxf\r\n"
			+ "three8five18\r\n" + "qsl69\r\n" + "gggtpfxg4threetwosixone\r\n" + "7twofourqx\r\n" + "fourdjg8\r\n"
			+ "two7one8\r\n" + "twobftgtppeight8\r\n" + "7bsprsvnrvlxzst6\r\n" + "twor934onetwo\r\n"
			+ "7ddblzjsevenrgntnfvfghxflmpttseven\r\n" + "fivefourfour2fourseven3\r\n" + "3hkhgknineonefour\r\n"
			+ "3fourmppdgkqlcbonesevensevenoneonek\r\n" + "8two99seven8x9\r\n" + "four1dfpb3seven\r\n"
			+ "eight2nine6tzlxz7drdrlzpmxeight\r\n" + "32nine7\r\n" + "8ppfgcbp76threefpdrlb\r\n"
			+ "two3zzrqn8oneone664\r\n" + "14eightcbftdbveightlksnckmr5four\r\n" + "6foursevendhrhmcbx\r\n"
			+ "8sixninethreezcv\r\n" + "mxzvkmrm43jvhqbrcxjjsnlbbtzdtf2\r\n" + "189fivejzrd\r\n"
			+ "sgmhskv8qmfvfhhh3\r\n" + "nine6jhbvfxsnbhqfnlnrtwo\r\n" + "five42one3fivesix\r\n"
			+ "2eight4eightthreecbdzmshjbgnine7\r\n" + "kt1mdzq2mfour3\r\n" + "52eight34sbksnnineone\r\n"
			+ "mzoneight5649chvkzxbnjx\r\n" + "mr8six1\r\n" + "fiveqspzvfxsqfhnfmqjzcone3\r\n" + "81four\r\n"
			+ "seveneight5twooneightbkq\r\n" + "onefour7one1\r\n" + "dmstwonerslbqeighthd2\r\n"
			+ "2eight3ninefivethreexlvns\r\n" + "583two\r\n" + "sixtwo589six22mbsq\r\n" + "943rljkqfour\r\n"
			+ "oneone946xnjsgsix\r\n" + "1eight6mlvbgqqtpr1nine8one\r\n" + "4eightqz32onefivexnrjlgdkv\r\n"
			+ "6qhbxgvvt4fivesevenfour\r\n" + "zlnztmlb345\r\n" + "1ninelsrrtzznvvtwopbc\r\n" + "ones3sixgtgvlnvn3\r\n"
			+ "xnpqnsjmg7jggkqsznhrg\r\n" + "smqtvjmsczbxqqcninejfone6\r\n" + "1three38qqvjnqjn5\r\n"
			+ "8onengjzrfeightgseventwo\r\n" + "9brrvfoursevendlfhgdl6\r\n" + "vkxtzgmttgtmgonethmbvltlz7\r\n"
			+ "k7eightfoureight8bjfch\r\n" + "two5j9\r\n" + "five94five47\r\n" + "twoxtzdgvmghrfphbbonellzkmeight14\r\n"
			+ "9hzrxd7\r\n" + "sixvtrpshzpxd7fthreeone\r\n" + "fivepzvm5\r\n" + "54hsbrxzg9two2gkdghhp\r\n"
			+ "3dxqhsmh\r\n" + "dsrxdpfpt16ninezeight2twotklstzd\r\n" + "sevenbslzfcglrsvqqgdptpcrtbrgb2five9\r\n"
			+ "ninetsbhxlkzfninebzjx2\r\n" + "nine8eight6\r\n" + "51sixclzmqnklzt1ggnqkdmtxszppl1\r\n"
			+ "ltwonedpgctq99stbsf\r\n" + "43nine5vxdblnjtthreetwo1mc\r\n" + "6fourbtbfqvjhrxbtdkj\r\n" + "kxz12one\r\n"
			+ "fourtfjvsevenmtsxqzxcznine2\r\n" + "26b\r\n" + "nine4mgcgnzrvxsvthreeonettclg\r\n"
			+ "sevenseven2kfxxoneninefour\r\n" + "2pxpsclrn32threefivefzvk9five\r\n" + "veight66jztz1sixnvpqt\r\n"
			+ "pgrlhz3four\r\n" + "fourfivefourninefklkdgdznllfgtj4seven1\r\n" + "sevenk1bn83\r\n"
			+ "3mmpfkdxtnvqfvnfivepmvmpsvhrrthreelzjbkgsrthree\r\n" + "fourfivefourfivegkjpmjh917\r\n"
			+ "1fivernjglptrkfqhnjzninejmqsevenone\r\n" + "lphthree8\r\n" + "nxqmkcg3\r\n"
			+ "sfsfdtseven9five1eightvcxzpzhqtc\r\n" + "5twosevenonefninefourzrbp\r\n" + "5spzsrnhlnthree\r\n"
			+ "sixnine7fiveqtwo8one\r\n" + "55fourtwonineonevjrdlqsone\r\n" + "44vtwo2ninesixcxrjzjs9\r\n"
			+ "qtxzfsdkmntckpthm2xpdb1fdn\r\n" + "nqzg1jch68kfdqjgdkfggvcgnmgstnine\r\n" + "555\r\n"
			+ "7threehhqdrgc\r\n" + "25six64eight\r\n" + "5four3sixthreethreefive3nine\r\n"
			+ "5twongscdpljqxhtchgfvdhzmdsqkdn\r\n" + "ljggbcbpk3\r\n" + "4fourbdnxshzz\r\n"
			+ "xdqczclsix8bmfjxdcdvmmkcscnjv72six\r\n" + "2seven3nine77two\r\n" + "twoeight7nststfmgzccv9tmrnk\r\n"
			+ "fivesrn7mvcnqkjlxbfivepzzctwo\r\n" + "1threerxzgffour3qcmtdshj\r\n" + "86lqf6\r\n"
			+ "jzclbmfj9zckkjpcdjxnkftrbfcqgdfmzvpdsjpfqp5\r\n" + "p9ntljjnzrqjlqfrdrkjbbkfourseven\r\n"
			+ "ssggbzchdsixeight7fivefive\r\n" + "326one\r\n" + "62three3p2rhmgvpeight4\r\n" + "29one2kr8\r\n"
			+ "xvrjgx5oneseven86eightrhlgpc\r\n" + "7eightfm6two\r\n" + "fqdj5four4twordncvxqsix\r\n"
			+ "3rctxbzfvnpgkdbfour5oneightcfq\r\n" + "fhbxgrdhtctfour5sixnflszkffour5\r\n" + "ndlmzp1nineninec\r\n"
			+ "7fiveljkjlhmfthree5five2three\r\n" + "13nine9one\r\n" + "xmcstmztxvxmrsixxzp8xdgzh3\r\n"
			+ "sconeightvnznvjxpxhsix7seven\r\n" + "two485seventhreeggkcrjtzg5\r\n" + "7vpsevencqlnftsx6hx\r\n"
			+ "six2kfjcgcnnjs4\r\n" + "ljlscdjmjxlhqcsevenfourmxfour9\r\n" + "eightfivelxfthreekcjzxkm9vk\r\n"
			+ "498vnxmgphh9one\r\n" + "ninenine85\r\n" + "6twonenhp\r\n" + "9tgnx\r\n"
			+ "ninexvrsmrphjpkbfvjqssevenfive8qgsjgnfrltm\r\n" + "8pcsbl52\r\n" + "five5klggkskxcthree32\r\n"
			+ "hjctwo6jvhmsqgsz\r\n" + "7sgzh82vpvtjtqjlmfnnpbl\r\n" + "3pdheight2two7tdqzjzdfive3\r\n"
			+ "pcptskpgsvx63twothgtbg5lmfbmkq\r\n" + "sz6three6fourfour8seven\r\n"
			+ "6fourpgfvsjsrjmdninehjvsixtvxzj\r\n" + "six3one71fourthreebzgjsxkptq5\r\n"
			+ "two531njqjsxvtsixckkfggxmkz\r\n" + "93nine1ninemq4mlxprdrcs7\r\n" + "736sixhsboneninefzfnhxhql\r\n"
			+ "jvqmrv32\r\n" + "2threetwo3twosxs\r\n" + "fiveeight2sixtmmttfbhtktgxgrvtk\r\n"
			+ "sevensixbpqx2fivevvkpkmlxrdxqtzb\r\n" + "nineljsnjgzzd6\r\n" + "two3seven\r\n"
			+ "dfour4fourqrqxmrmqlzfzzrmd\r\n" + "26two4jkcjczoneeightpxb\r\n"
			+ "twosmfpjqlhlkdqtjqvqslkzhx8threetwonek\r\n" + "twojbt3\r\n" + "eight6ninexhztllsnineonefive5\r\n"
			+ "jxscfpmcfour2ksmgthreevbtvzxxrqmtznqqcjzghv5\r\n" + "5zsmdlsevenninethree\r\n"
			+ "vnnmbgxjdzdcrhpm22nines\r\n" + "7sevendzsxrboneone\r\n"
			+ "one19njgspzjvpllfcznbqvthreetjmzbhtmzknfrqf\r\n" + "sixsixsixhqn22six1bdckxsfj\r\n"
			+ "xsevenseven65n\r\n" + "twohbfvzvkpzjrmzdreightmrrkl7eight\r\n" + "pxtvbrlqbztqxhvcrrf55\r\n"
			+ "qtwogljlgnz53\r\n" + "seven2ninetfzzsmgzfour9twomgzjnnbdfv\r\n"
			+ "mptlphqjnpbbjbj3dgpvnttseventrmjlnpbxgkbchsszh\r\n" + "5qnhsjdtc9one7\r\n"
			+ "vsdgvjqvfivefour3qmvfxmdfn5gkkthrsfnq\r\n" + "2zqhrl67three6\r\n" + "52six\r\n"
			+ "t7one5gcksv41ftknzgdpskrtwonekf\r\n" + "ngqfhbvonesix49six4ck\r\n"
			+ "gjcclbdp2twothreejlgcmmvdldpnfnfdhcdrgxeight\r\n" + "sixpvzhqtzt2five\r\n"
			+ "fivefourh6zhfbtlcfvfsvbtcrone5\r\n" + "threehjdl27sevenftfjpnpninethree\r\n"
			+ "seven2qffourtnbrtslmbrtzrbss\r\n" + "5nine3onesix\r\n" + "mpkksrpzpcnjceightcrfsjhl9rfmxkhzkvpnvzck\r\n"
			+ "rlqxvhcmfiverqlp86threesixnineseven\r\n" + "two9three\r\n" + "1hrqsrsqk\r\n"
			+ "s8jvshkhmsbjnnzzvzl1threefour5two\r\n" + "hdq6bvlrtwo\r\n" + "2mfzlkfflfive\r\n" + "42nine176\r\n"
			+ "2onemgfxnxbsvr4\r\n" + "six5onegkvfxktggkrmnjhsevenfournjbm\r\n" + "onetscccxrrbd5fourqlvqtfknr3\r\n"
			+ "twonine5\r\n" + "zftwoeight3six815four\r\n" + "1oneightq\r\n" + "seven8nineninegjstgcs1\r\n"
			+ "sixonefive996\r\n" + "57qr7p59kx\r\n" + "vkvfqlrdcnlsfour2tcjc8nine\r\n" + "bbxsstbrnmnine99zcpp2\r\n"
			+ "6psfcj7fiveoned9pxk1\r\n" + "stndz8q9\r\n" + "7seven1gcmvm2zlflone\r\n"
			+ "sixmmkconefznkdmhfivetwobfbrlvfive6\r\n" + "7qblvlssb\r\n" + "bxlpnjhkvx1bzjgj5515four\r\n"
			+ "sevenjnine2\r\n" + "hqrmgtbhlrbchqld6fh6oneseven4ssfkhm\r\n" + "3zpjqqgtk9\r\n"
			+ "4zr8pckql23mlsfvr1\r\n" + "8zpdxmbdj\r\n" + "vdtgghlr9dqlkcbtjcptqftone2\r\n" + "7phhnj1hvnpznone\r\n"
			+ "seven1three\r\n" + "bvzqkpmxlplv4threezjkpbbngtgfxslhczq\r\n" + "eight353fourjbthbjzrxk3\r\n"
			+ "1vszpmreightqkcbpmgvz\r\n" + "two8gdjbjnsix5mpcjd\r\n" + "ngtltwo8cvdhtpnine\r\n"
			+ "eight7seven57four234\r\n" + "316xqvstdslj\r\n" + "three2dxhg4one87mblcfljtrhoneightb\r\n"
			+ "seventhree1646fivefour\r\n" + "3twojplhronenine\r\n" + "6fpv43gnzm\r\n"
			+ "qncbbfkfceightngdnxkllfourone6\r\n" + "seven238\r\n" + "76vdsxpfngdpslhkh8\r\n" + "two86\r\n"
			+ "5zfmlbpseven\r\n" + "8twosix\r\n" + "fiverg414vvlxccjx6\r\n" + "7vbptbclkkrlnt24threeseven\r\n"
			+ "four36crrfour29\r\n" + "sixlfivelqqmbmcxvfkpdfpfzsix39nine\r\n" + "smmfd9vczg2mhsjdnvgtnine\r\n"
			+ "threefgxqhtrln7scjxkndonetwofive2khzx\r\n" + "4threejtrblf3774nzndnnjvf\r\n" + "cthree9bzd65\r\n"
			+ "869foureight\r\n" + "6jknfthxptgjlzqjznjpbthz\r\n" + "mmhgmpncgctwoztseven8th2fncrcvmckxxhxzmqxl\r\n"
			+ "9zmmt6sevenfive\r\n" + "fnstwonensgnkrrgrm333onetsckzm2\r\n" + "1five6eightnine1five1seven\r\n"
			+ "1tjvvbtsbr1four\r\n" + "eightsevenfivesixthreefnlgzpkffive3\r\n" + "4eightmfjxkhddrxrttzffdnthree\r\n"
			+ "9seightone\r\n" + "dfcscfour8\r\n" + "58vfjhqsz44dktkdbcggvzrxonesqqqfzmp\r\n"
			+ "fivefourhghrmjbtrdseven7five7tdlmtxhv\r\n" + "qjcjcthreefive64\r\n" + "ppcndxtgzqsqfqq9sixonefourrkf\r\n"
			+ "f5chjf9seventwosix4\r\n" + "tmtzhrbzqbtsfbbkr25rqv6pgz\r\n" + "3svvptrmnxgsqpgppvseventhreesix1\r\n"
			+ "d5fivessix\r\n" + "8br\r\n" + "834fivemrhnnjmbf\r\n" + "eightlzbtqrrfvxhhnx6vbxvzdt2eightkz2\r\n"
			+ "foursix51lfnpbkczk8twosixeight\r\n" + "2nzjhljckdfiveeightfive\r\n"
			+ "lxftlsgrrsrgqntqxcbnp3threeseven\r\n" + "lhpzv3hkcsbhnq7\r\n" + "kdfzdtxlqbfive9\r\n"
			+ "threedhqseven8eightseven\r\n" + "7tbtlpsmzlbkfzcdbmndfvgcxcqtfzmdhqktwo5\r\n"
			+ "krhqqrsixseven72jxhgchzgcmtrthtqnmmnpttc\r\n" + "1xxfvpvlzjfive8fivefivekjfsq\r\n" + "five13\r\n"
			+ "1fivexgsgk785vmdlgf\r\n" + "14fourbrg65\r\n" + "1onesmprhxsone1fourkt\r\n" + "twoclk8\r\n"
			+ "fivenine4d\r\n" + "six3seven6\r\n" + "svcmfmqfsevenonesevenbhsrptwo2\r\n"
			+ "4onefivevznngdbffour5scjxpftpnhtwo\r\n" + "vvmgdzrfldhsjflseven5eight54eightnine\r\n" + "jpc54\r\n"
			+ "threenine65fivekvms\r\n" + "eightfsixnineseven2three\r\n" + "three43fcfrbmpmgthreerpxshkfcfoneeight\r\n"
			+ "8jmvvgmltvzlqjonevdtdpvngtwocxcthree\r\n" + "dlxth8\r\n" + "two58\r\n" + "6k5sixseven\r\n"
			+ "vfkpzmrxlcfhj7szfcpprjbdlzltmkkmj\r\n" + "8ltv4\r\n" + "1twofkcpppq\r\n"
			+ "five2sixfour6dthpckzrzxspjptdxxkfmn\r\n" + "3eightdkkone2onex54\r\n" + "fouronerpn5sevennine4three\r\n"
			+ "2gjbxsgsgt3nczpbdf\r\n" + "4ngvcffpgfx9hzxkvmsfsevensix1\r\n" + "5smqrqkseven4ttjrnnjfsh3gbfkgfivesc\r\n"
			+ "sevensixsevennine5f48six\r\n" + "2fourdmdone\r\n" + "fourtwo5zsrhxmjkn43\r\n" + "bchrtcnltseven6\r\n"
			+ "vtwone9dfeightfiveghzbgonenlckrg\r\n" + "1twothree22\r\n" + "twoqtt58threeklrpkhlc3\r\n"
			+ "bnmq4fivegc\r\n" + "dqffiveninenine4tnsrk375\r\n" + "pgeightwo6tsevenseven9seventwomnfcvglsf\r\n"
			+ "27eightpbbkn9zzldxqplzjthreetwo\r\n" + "vg6\r\n" + "lnsnglzsm96nine8\r\n"
			+ "one2bgmmnvnbtlxmnbjk3vvtqlqtwothreeeightwokbd\r\n" + "9three8two\r\n" + "fgxfbthree8mbpplseven3one\r\n"
			+ "four346sevenjxrgkxf2\r\n" + "three5qjsevenninetwo\r\n" + "oneseven4497one1rmkljk\r\n"
			+ "cvfcmsqcscphlseven6four\r\n" + "threeeightsvsps3\r\n" + "3pcqgqkcpgnzlkxnneightonehzgsix\r\n"
			+ "mpeightwosrfpfq2bztpmhx\r\n" + "4fourtwoqfbhrlzjmcc\r\n" + "sixtwokm4tpcsfour\r\n" + "58one\r\n"
			+ "pdbpzhptjfhfive4nine6\r\n" + "3three3threedqlmbonethree99\r\n" + "7fhldqcxbdlbdggtm9six98\r\n"
			+ "g1one22fiveone1slpzmtcn\r\n" + "sevensixbmpg66four7cqcfxg1\r\n" + "lvpcjshtwotvdnxkqzv4\r\n"
			+ "4tbmmgqxdsr54seventhree8four\r\n" + "99oneonedhvr1\r\n" + "3tfszvjgrbf\r\n" + "one2nineztqchrz\r\n"
			+ "bfnnlh5nnzltmqlx9\r\n" + "gcsmzxlvssix5lkmk1\r\n" + "hv4eight5\r\n" + "8clgggvkkcj3\r\n"
			+ "pmkvsixfive2\r\n" + "5lk5\r\n" + "8four7qeight\r\n" + "xxfgflhgqnine96gdqcdqlrhfive\r\n"
			+ "vpdmcz1223seven3\r\n" + "gt7fivenineeightchbfrvbtl2foursix\r\n" + "eight86qtm5\r\n"
			+ "4rzcxqz4five8fhdfmdksthree7eightwom\r\n" + "fourtwo3three2\r\n" + "38ninezlzdp8fourqrgjc\r\n"
			+ "1959\r\n" + "8mvnhpvkddhtwonghtlpq\r\n" + "dbd2xttfllfp2\r\n" + "23eightseven\r\n"
			+ "53nine77qzbsrpgsg\r\n" + "xbd4onethreechblfshmeight\r\n" + "837sixbxtjfivetprgjjd\r\n" + "62six\r\n"
			+ "1fivegfklmmqnkrdnvrpjpcnlzbveight\r\n" + "five632pqcksmxlrznqvjcmlttqhh\r\n"
			+ "twoeight9jgmjxpjjxjhxz\r\n" + "pmt83fourone7sevensix\r\n" + "578twonmpvzzvd7\r\n" + "six9six\r\n"
			+ "2xczcgszvrl25fivefourgvkhtcfhqmbggrneighteightwopqt\r\n" + "5oneseven1\r\n" + "seven3onexg\r\n"
			+ "sixpvrtxqlmrqbz9five89seven\r\n" + "8eightp2six\r\n" + "3thtzqgpzkdvfivenine\r\n" + "17942twonebcl\r\n"
			+ "ninevfcseven34n5\r\n" + "five3dt3\r\n" + "three6knn\r\n" + "jsmmgrjsix5zqsnbfmgjlmrptqzvzmjr7brm9\r\n"
			+ "3ll7992243\r\n" + "8fourfonemhtmkrht8rhfdljqb3five\r\n" + "threefourgxbvvrfourtqnrf7\r\n"
			+ "3v27nine\r\n" + "3lklpsnf\r\n" + "39sixjpdbd7sevenhc\r\n" + "oneone1\r\n" + "9vft\r\n"
			+ "2pnrfourbhv5frsgpjfnh\r\n" + "7zqqfldgq64eight84vsbrdhscnc\r\n" + "5q4kxgjnxoneninethree\r\n"
			+ "threemllvrszngnthreenine6\r\n" + "3ninegkshrtnlccsixeightsixf6\r\n" + "5two47\r\n"
			+ "9jnkpcfnxeight674brdflkbd\r\n" + "66sixsixzpgq\r\n" + "onesvcmtlhrrslxsktjfbkz9eight58\r\n"
			+ "vprnflbkbnsfsmfkfrmrdfbjhk4tworqsbonethree\r\n" + "7onetwogmskgscbtxeightsqgfvvc4mlttvhgt\r\n"
			+ "7nine6141t4pqlgvc\r\n" + "knbvjgvzpm3pztzzqmntxcgvjn\r\n" + "tprneight9qxzqslmm7fivefmxtxn\r\n"
			+ "6xvvjbcdfoursixone5eightxztjztzpgsix\r\n" + "24six4s6sixnine\r\n" + "oneqlppjrfqsevenhgqlxkdhqx8s\r\n"
			+ "8nineeightc\r\n" + "jbconeoneeight9frgxlrdhzlcrzshjknxmfrmqmh\r\n" + "561nine8zhxlhcrmdj\r\n"
			+ "5qtmn17ninephlnsqpts4two\r\n" + "nznsfgmddt1nine\r\n" + "gsmqltczf6qpm\r\n" + "fourfmhl8bvgv\r\n"
			+ "six8blfivefour\r\n" + "one6fjm\r\n" + "tvsdnjt72five3seveneight\r\n" + "7threekkxlzcgrfvltwo\r\n"
			+ "mtxeight1one443six\r\n" + "pgsfz6sevenfour\r\n" + "13mfzcpgtbzsdcbqtmhlll\r\n"
			+ "mftjkvxqpninefjbone1f\r\n" + "sixtgrfmjl97fsjhgcsmmp4\r\n" + "cqsksrkqqp7cfvjkrptsjdsk3\r\n"
			+ "xhphdkvtjzgkmvbj1fourj1sixone\r\n" + "foureight86three4one4\r\n" + "5threep7kfkznmhj28\r\n"
			+ "sfvpqfivem9fiveone\r\n" + "912fourztbndhpbzcbc\r\n" + "mbvpzgeightseven48eight\r\n"
			+ "mfpq528cvgxnv7\r\n" + "xbeightwo78five\r\n" + "kqngfmq5sevenddchr9\r\n" + "4threevvt8\r\n"
			+ "hpxsdjdksix2\r\n" + "2r\r\n" + "9four32four\r\n" + "8twotqhxgj47\r\n" + "6sixsfgbheighth\r\n"
			+ "njmljrmtsevensix21phkczzeight6seven\r\n" + "twomfklfdqvmbdnptfssrrjdfour9\r\n" + "6five3\r\n"
			+ "tjzqzdmkj2qt13\r\n" + "twocjncqgm7one5sixfour\r\n" + "fivefourjtvqxchf5cgf79kmlcsd5\r\n"
			+ "7nsrjmcleight1threenine\r\n" + "lvstq3tn1\r\n" + "twotwo44\r\n" + "noneight5msix2qdpb87g\r\n"
			+ "9rp3dtp21four2three\r\n" + "5fouronejmpdq2two7nine\r\n"
			+ "poneighthvhkbvtvxzmljfhrmf3fourbdcssgjtbht\r\n" + "sevenninef5\r\n" + "eight9oneeightsix9three\r\n"
			+ "eighttwo841\r\n" + "6nine45ninetwo1\r\n" + "bsrtmkplhbjbrsbjsrzpbfxpvj87onepkc\r\n"
			+ "9fivephcqlsln9\r\n" + "xftntmjsb168rjjvv5five8\r\n" + "frfr628vrbrzg\r\n" + "kqgz3jms56six83six\r\n"
			+ "threefourfourtwo2p\r\n" + "rrxdjjgrfmkzqrqtdg7onefour\r\n" + "oneksqkxk8315cjtxhpl\r\n"
			+ "pmfmf7six2\r\n" + "xfdmvhmrfbfour7\r\n" + "36sevenone\r\n" + "nine25bfivedhgch1\r\n" + "cpvrs97twod3\r\n"
			+ "fivesix23six5\r\n" + "95pkmbpphdmninenthphrzknhgvzfour\r\n" + "5mqlkhqfzfive3bscfcnine\r\n"
			+ "8eightvmbhccqkvmpsnjxxfourpng\r\n" + "twok4\r\n" + "4one8dlrtdgbkxthreetwo7\r\n"
			+ "4spvdztldx93twor93one\r\n" + "cfl7\r\n" + "vgfzjqhfvz7onefivevkqvrxtkmone\r\n" + "7fourtwofour\r\n"
			+ "fivemscxhgtrcsone2jjr1\r\n" + "htbrrlrgkvgpbhcqtn5ninefournine2x\r\n"
			+ "bttjgdnnmlrljsltxrbzjqhnbfghcktt5fivebfqbgsvt\r\n" + "sixfivefive977\r\n" + "bqzqdh38ninesix\r\n"
			+ "hmghtzdgqnlh7\r\n" + "threenine4\r\n" + "5sevenseven\r\n" + "5qphzsdgsxhnfivesixeight\r\n"
			+ "5zhdfpvk6seventhreenine\r\n" + "jrtrsevenfour9seven\r\n" + "kzvlczdmvlmlnjqrbgjdtwosix8rqhjjkffz\r\n"
			+ "bmjmv869\r\n" + "four7three\r\n" + "six1five34\r\n" + "7zchsmjgqnqffzjktfourcchdhzxjmsix\r\n"
			+ "5cprgcs5bvjqgkqrqc2\r\n" + "fiveeight5gkk\r\n" + "14nine2eightxrqqlthree98\r\n"
			+ "four5nine5nzgrrgqpnkpkbone\r\n" + "2foursevenqzqgzone\r\n" + "oneqjcplbtdqcfourmktsjbjhgeight4\r\n"
			+ "9nine7four6\r\n" + "dqcjqvmmhxthree2seven\r\n" + "11bvnrsbkgtzlrvhdhqk\r\n"
			+ "fiveseveneight9twosmcmcmmdx8eight\r\n" + "seven8qvgppnbkggrjlqthree\r\n" + "83ntsixvdvkhlzseven\r\n"
			+ "7eighthfxgnqclk\r\n" + "sevengxzone4fivexcfffdxg7pjxjbb8\r\n" + "eight84eight46\r\n"
			+ "52clgxx3npppzfournqtbpvsnvjpteightwomss\r\n" + "tctwone4dbqvnvf\r\n"
			+ "pfsgbkfivetworpqtbbfs38nineoneightjg\r\n" + "37eightfourthree\r\n" + "1eight2ndctgkcbmjmthree\r\n"
			+ "vmcxzmmzvk63fllrlg4one\r\n" + "cmjpxqkmfouronenine3twojplnvfrncone\r\n" + "seveneightpjdbx3twoeight7\r\n"
			+ "143klgccxcmcteight172xgqlmmkfjp\r\n" + "fbrhrjcmljtsfqhtms614threeninendjjzpdpzp\r\n"
			+ "8hrtbrvxssixtwo6four4vgttssxthree\r\n" + "szfr671\r\n" + "73njhhjpxlflhmdqrtzgm3\r\n"
			+ "gglrxone97four83nine\r\n" + "rz8\r\n" + "3lxvdvgvsnmhfqcmgrqgf7njqfphdnxj\r\n"
			+ "eightsix9crbjrtcvlzfive3rffgxsbcgqpxdczmv\r\n" + "two4kfqbcrz7eightfsdfzrreight\r\n"
			+ "2sevenmcxcqpbpjgoneseventhree\r\n" + "one4four6lphcmhnd\r\n" + "79\r\n"
			+ "dnnzzhqthtwosevenlfgxbzlxnclzbksevenh6eight\r\n" + "twoseventwoqgjbjvxfmsmnslrbbhvn8nine\r\n"
			+ "13jtmqsdninetkf\r\n" + "three7fourseveneightngbrsgkrtfltffksevenr\r\n" + "jlpm5fourxkrldrzbmjbddptd\r\n"
			+ "four91sevenone1lkbfxhl\r\n" + "gnqsbnck1two\r\n" + "19nine3five7tkzjfour\r\n" + "vqjg22four9eight\r\n"
			+ "1threeeight7cn\r\n" + "3vnxjcc5threefiveone5\r\n" + "fiveltjstjtpr76zsixjvkkb\r\n"
			+ "xbdnrjgplmrnfn59two6mfhsphtsmgxgpzsp\r\n" + "4jb39ninebfr\r\n" + "jz1xpbtspgb7\r\n"
			+ "fivesixsldbpmjpnkxlfour1l\r\n" + "stvdtqtrrtdvplxtfjlbnbs9oneg7three\r\n" + "two9eight7four\r\n"
			+ "nine395five3\r\n" + "2zl23threegrqdbkfourkfqh1\r\n" + "1mzdslsbsevencccphxpdbtzqj1\r\n"
			+ "6nhtfsmqfdssix67\r\n" + "sixeightdhbvdnrb2six2\r\n" + "1sdqrzsfr113ninertcrbhthreekrttgbj\r\n"
			+ "lone9xdhfive48\r\n" + "xhgqjgcdneight2\r\n" + "ninefouronez14srhgxtqd\r\n" + "dzvbvpronenineb3nine\r\n"
			+ "kczhrrthreesixeightbhcccxlqkj2djfqrlfc\r\n" + "five5five2ksgn\r\n" + "threefourjfqzlgtvv8pfx31v\r\n"
			+ "1fivejlvfqjhsm\r\n" + "four6972fournzmpchninegddxrfh\r\n" + "12nine\r\n"
			+ "2nrsgtdlddhqdxhqpljtfourppeight\r\n" + "bbqrgsxlgptbqplhs8pkone\r\n" + "5nineztvqdnine744\r\n"
			+ "tsrkfddkc1three\r\n" + "9sixone9nfbksgbfpfour24three\r\n" + "98lztb\r\n"
			+ "oneeightfnhtkkhfqtpfpdhqjbpflhhzf463\r\n" + "one9kmhghftf7qsmztntzx92\r\n"
			+ "xzzpjmqlxnknk543vdfgldvfdrbnnfttmtqzfh\r\n" + "dq74twosixfourfiverfbxzvjtfv5\r\n"
			+ "lqrnlzvxngfcsgg9dmpjjlgfm6two\r\n" + "ninejhxqrtfrstwo22dxnvfmtbscrkzc\r\n" + "txjeightwo21\r\n"
			+ "qlsix459ttqtsfzg\r\n" + "bxbeight15fktzb3vjxbnkck6\r\n" + "53twohbrqgtd\r\n" + "mfztbczrqltfivesix8\r\n"
			+ "9lxtnpzffczvhssfb\r\n" + "fivehtzrxsrm19\r\n" + "1ctslhhtwo1\r\n" + "five6zsix1gbjhklpszlkmszcj\r\n"
			+ "4shtgrkninevqntzltrhhflgrhsslz9one\r\n" + "four3tsk45\r\n" + "hpkt8eightsix\r\n" + "5nine9two\r\n"
			+ "fourxvkjdkdgbklcnzmhqtgdq1\r\n" + "1foursxbrk43mzfjxqrsloneseven\r\n" + "lsbhfoursix9sevenone7\r\n"
			+ "vtnxseight1ndlxgleighttwosixthree\r\n" + "5gsfbrqtfkz\r\n" + "sixonetpfnznvrnxhgcqkv6nine\r\n"
			+ "3rhbcklhbtqljqheight7\r\n" + "zhtkqb1rsntcgnq85gftptxqc8\r\n" + "shhmqrgdpvscvkcdpks4\r\n"
			+ "nineninenine2three5two3\r\n" + "trfbhljnl9nine\r\n" + "sixlcmnpkdlqr6\r\n"
			+ "qhdrmdjbmczfdjqfxv7eightwoxt\r\n" + "n4nkjlfx8seveneight\r\n" + "46eightgjnhsx\r\n"
			+ "mbeightwo4jbcgxprkjrjspf\r\n" + "ninemq9sixvrdqmr\r\n" + "fourkxvmmdf87pfzjfdpthreex\r\n"
			+ "9ninebp1\r\n" + "1four2kghfdgtgdx\r\n" + "5hrlslhpnine4seven4bzjttvtv4\r\n"
			+ "xcqqrxdkdsckqtnvlqh9three\r\n" + "8sixnine\r\n" + "9fourthreesixzglsqrmgtt8\r\n" + "2onetwo\r\n"
			+ "98kgnrkdvjfeightfive5tkffmq\r\n" + "7mrjskhffjqeightfiveoneonethree\r\n" + "7lgfcqvthree8bvlk2kf4\r\n"
			+ "2xstvqxnsggkxvfrllzkseven9zqtwo\r\n" + "xjqcvvh6two\r\n" + "2seven8gjdgmg\r\n"
			+ "ghvzpxlgfhctwortxvlfkxl1tqkthbddfhpzdjklk3\r\n" + "nineninernvpzsbnine2ninenbrkbkdclc6\r\n"
			+ "29twojsvrz7eightzhznhflcld71\r\n" + "eightthreefive5kkgcconepmm\r\n" + "3tlz7fjzpgnvfgdgqbrqqsv\r\n"
			+ "mcp213six4jjqtgxpkzh\r\n" + "one7nineqnjsgcjnjmdhdrxbthree\r\n"
			+ "xzvxcvpdftpllcxvpbtwoxkspeightvmfhlqxklthree1\r\n" + "nnzksztgtpfour61mfjmvnonezgvhdg\r\n"
			+ "qkj6one5one49g7\r\n" + "threesix6eightlxdkttbbcz3bbvgnxjnjf\r\n" + "3fivenine\r\n" + "3sixhmbnfrk\r\n"
			+ "7qcjzchtkssix\r\n" + "vsfour5nqjjzmx\r\n" + "cdxhcsrhvc3\r\n" + "47hjzgbpsixjjfsbhninerfbrvf\r\n"
			+ "seven8sevenptdlvvgssixvjvzpvsp7fivefourtwoned\r\n" + "ctwonezxpflzeightczjnvj7173eight\r\n"
			+ "ldklqc91fiveeighteight9\r\n" + "pptwo6sevenfivevlgs8threegbpc\r\n" + "ctwoneone7dtztzrk3ninefivexvj\r\n"
			+ "1oneninegspfm3four43\r\n" + "sixfourgkdlxtqmbzkgmpmcsevenhzrt4\r\n" + "eight6twojtzlvlhgjncvx\r\n";

	public static int calibrationValue = 0;
	
	public static void main(String[] args) {
		Arrays.stream(INPUT.split("\r\n")).map(Trebuchet::extractNumbersFromString).forEach(Trebuchet::generateCalibrationValue);
		System.out.println("Calibration Value:" + calibrationValue);
	}

	private static List<String> extractNumbersFromString(String input) {
		List<String> numbers = new ArrayList<>();
		for (char c : input.toCharArray()) {
			if (Character.isDigit(c)) {
				numbers.add(String.valueOf(c)); 
			}
		}
		return numbers;
	}
	
	public static void generateCalibrationValue(List<String> line) {
		calibrationValue += Integer.valueOf(line.get(0) + line.get(line.size()-1));
	}
}
